Set calendar months statically.
Avoids setting the locale.  The docs say:

   It is generally a bad idea to call setlocale() in some library routine,
   since as a side effect it affects the entire program. Saving and restoring
   it is almost as bad: it is expensive and affects other threads that happen
   to run before the settings have been restored.

Besides in some environments this fails with:

   Error: unsupported locale setting

See https://gitlab.lahavane.com/mercurio/xhg/-/jobs/11076

Fixes #20.