Don't require statictype in Python 3.10
Since 'NoneType', 'EllipsisType' are now in Python 3.10, mypy will complain
about:

xotl/tools/future/types.py:43: error: Cannot assign to a type
xotl/tools/future/types.py:43: error: Incompatible types in assignment (expression has type "Type[None]", variable has type "Type[NoneType]")
xotl/tools/future/types.py:46: error: Cannot assign multiple types to name "EllipsisType" without an explicit "Type[...]" annotation