Fix error for 'deprecated' function in Python 3.
There are cases where a class being deprecated doesn't define '__new__' part
of constructor.  This commit fix this issue.

For example::

  >>> @deprecated('any')
  ... class foobar(object):
  ...     def __init__(self, target):
  ...         self.target = target

  # In the former version
  >>> foobar(1)
  TypeError: object() takes no parameters